version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - nw-1

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gh_archive
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    ports:
      - "5432:5432"
    networks:
      - nw-1
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - nw-1
  af:
    build:
      context: .
      dockerfile: airflow.Dockerfile
    ports:
      - "8000:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/config:/opt/airflow/config
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
    depends_on:
      - db
    networks:
      - nw-1
    command: >
      bash -c "airflow db migrate && airflow standalone"

  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
  
  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./dbt/usr/app:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app/gh_pipeline
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    depends_on:
      - db
    networks:
      - nw-1
    command: debug

  minio:
    image:  minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # WS
    environment:
      MINIO_ROOT_USER: xpham
      MINIO_ROOT_PASSWORD: xpham_minio
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    networks:
      - nw-1

networks:
  nw-1:
    driver: bridge
    